export const RECEIVE_ADDRESS = 'receive_address'
export const RECEIVE_CATEGORY = 'receive_category'
export const RECEIVE_SHOPS = 'receive_shops'
export const RECEIVE_USER_INFO = 'receive_user_info'
export const RESET_USER_INFO = 'reset_user_info' // 重置用户信息
export const RECEIVE_GOODS = 'receive_goods' // 接收商品数组
export const RECEIVE_RATINGS = 'receive_ratings' // 接收商家评价数组
export const RECEIVE_INFO = 'receive_info' // 接收商家信息
export const INCREMENT_FOOD_COUNT = 'increment_food_count' // 增加food中的count
export const DECREMENT_FOOD_COUNT = 'decrement_food_count' // 减少food中的count
export const CLEARCART = 'clearcart' // 清除购物车
